<?php
function greetings_menu() {
    $items = array();
    $items['hello_friend'] = array(
        'title' => 'Hello Friend!',
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farwell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function say_hello() {
    return '<p>HHELLO BACON CHICKEN APPELS</p>';
}

function say_farewell() {
    return '<p>GOODBYE DOUGHTNUT TURKEY CIDER!</p>';
}

function greetings_user_login() {
    $_GET['destination'] = 'hello_friend';
}

function greetings_user_logout() {
    $_GET['destination'] = 'farewell';
}
